### PR TITLE
Issue67

### PR DESCRIPTION
**Pull request by markanewman**
PR for #67

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Would you mind making a unit test for this?

**Comment by markanewman** [comment]
I did try that, but there is something wrong with my VS setup for this project. When I go to test runner, nothing happens. The build ticks off just fine, the output window reports success, but then nothing happens. I am use to the green lights showing up in test runner, but there is just nothing there.

Any ideas as to what might be up?

**Comment by SergeyKanzhelev** [comment]
I haven't seen errors like this. @cijothomas, @dnduffy ?

**Comment by dnduffy** [comment]
@markanewman Try exiting all instances of VS and restarting one instance and reloading the project.  I've seen this behavior before although I don't know the specifics or why it sometimes happens.  For me anyway one solution was restarting VS from scratch.  Another thing to check might be that you have the latest updates installed for VS and the latest packages installed for the unit tests.

**Comment by SergeyKanzhelev** [comment]
@markanewman have you had a chance to add tests to this PR?

**Comment by markanewman** [comment]
@dnduffy I also tried to reinstall VS and still no dice. My unit tests in my other projects work fine. At work we are federated with MS, should I try to contact you directly and do a screen share?

@SergeyKanzhelev If I can't get the unit tests working, should I just abandon the PR because I cant prove the work?

**Comment by SergeyKanzhelev** [comment]
@markanewman this is a good feature - so please do not close PR yet. I'd ask you to try one more thing with Unit Tests before passing this PR for us to update and complete.

Did you reinstall VS on the same machines? Are other projects you mentioned uses VS tests or NUnit or xUnit? Does output window (make sure to switch to `Tests`) shows any errors? 

Here is a [long thread](http://stackoverflow.com/questions/29560011/visual-studio-2015-does-not-discover-unit-tests) on which folders could have cached bad files. Could you please try cleaning those folders.

**Comment by markanewman** [comment]
@SergeyKanzhelev I reinstalled on my primary PC. I also tried to load the solution on my Surface, same thing. I us the default MSTests in VS. I will try out the PS script you mention in the link later today and report back.

**Comment by markanewman** [comment]
@SergeyKanzhelev Still no dice. It just wont pick up the tests.

**Pull request closed without merging**
