### PR TITLE
Added two properties on telemetryClient

### PR DESCRIPTION
**Pull request by naveednawaz**
#178 
In this way, we can add Cloud.RoleName and Cloud.RoleInstance

### CODE REVIEW

**Comment by pharring** [comment]
Consider what happens when those properties are modified after the telemetryClient Context has already been set in InitializeTarget. You could either have the setters throw or relay the value to telemetryClient.

**Comment by SergeyKanzhelev** [comment]
@naveednawaz what is your scenario? Recommended way to set role name and role instance is to register corresponding telemetry initializer. Like:

``` csharp
TelemetryConfiguration.Active.TelemetryInitializers.Add(new DomainNameRoleInstanceTelemetryInitializer());
```

If you need to set custom values declaratively - potentially better solution will be to implement https://github.com/Microsoft/ApplicationInsights-dotnet/issues/630 which will allow to set role name and role instance for entire process. Or you can always implement simple custom initializer.

Drawback of proposed solution is that those properties will only be set on logs. Not on any other telemetry. So you'd loose ability to correlate different telemetry types.

**Comment by naveednawaz** [comment]
@pharring  
I have added these properties exactly same like existing instrumentkey property. It's should work as instrumentkey

**Comment by naveednawaz** [comment]
@SergeyKanzhelev 
I want  to use nlog target and add role name. Telemetry client is not accessible from applicationinsight target class.

**Comment by SergeyKanzhelev** [comment]
@naveednawaz can you explain why setting role name globally like this wouldn't work? Like this:

``` csharp
TelemetryConfiguration.Active.TelemetryInitializers.Add(new DomainNameRoleInstanceTelemetryInitializer());
```

**Comment by naveednawaz** [comment]
@SergeyKanzhelev
Can you tell me how can I add RoleName in this sample code by using 
TelemetryConfiguration.Active.TelemetryInitializers.Add(new DomainNameRoleInstanceTelemetryInitializer());

Console app (Install-Package Microsoft.ApplicationInsights.NLogTarget -Version 2.6.0-beta3)
var config = new LoggingConfiguration();
ApplicationInsightsTarget target = new ApplicationInsightsTarget();
// You need this only if you did not define InstrumentationKey in ApplicationInsights.config or want to use different instrumentation key
target.InstrumentationKey = "key";
LoggingRule rule = new LoggingRule("*", target);
config.LoggingRules.Add(rule);LogManager.Configuration = config;
Logger logger = LogManager.GetLogger("Example");
logger.Debug("trace log debug");

**Comment by SergeyKanzhelev** [comment]
``` powershell
Install-Package Microsoft.ApplicationInsights.NLogTarget -Version 2.6.0-beta3
Install-Package Microsoft.ApplicationInsights.WindowsServer -Version 2.6.0-beta3
```

``` csharp
TelemetryConfiguration.Active.TelemetryInitializers.Add(new DomainNameRoleInstanceTelemetryInitializer());
var config = new LoggingConfiguration();
ApplicationInsightsTarget target = new ApplicationInsightsTarget();
// You need this only if you did not define InstrumentationKey in ApplicationInsights.config or want to use different instrumentation key
target.InstrumentationKey = "key";
LoggingRule rule = new LoggingRule("*", target);
config.LoggingRules.Add(rule);LogManager.Configuration = config;
Logger logger = LogManager.GetLogger("Example");
logger.Debug("trace log debug");
```


Alternatively you can define your own initializer:

``` powershell
Install-Package Microsoft.ApplicationInsights.NLogTarget -Version 2.6.0-beta3
```

``` csharp
public class CloudContextInitializer : ITelemetryInitializer
{
  public void Initialize(ITelemetry telemetry)
  {
    telemetry.Context.Cloud.RoleName = "role name";
    telemetry.Context.Cloud.RoleInstance = "role instance";
  }
}

TelemetryConfiguration.Active.TelemetryInitializers.Add(new CloudContextInitializer());
var config = new LoggingConfiguration();
ApplicationInsightsTarget target = new ApplicationInsightsTarget();
// You need this only if you did not define InstrumentationKey in ApplicationInsights.config or want to use different instrumentation key
target.InstrumentationKey = "key";
LoggingRule rule = new LoggingRule("*", target);
config.LoggingRules.Add(rule);LogManager.Configuration = config;
Logger logger = LogManager.GetLogger("Example");
logger.Debug("trace log debug");
```

**Comment by SergeyKanzhelev** [comment]
@naveednawaz from my understanding of your scenario - proposed approach may be better that suggested changes. But you know your scenario the best - thus my questions to better understand what's missing.

**Comment by naveednawaz** [comment]
@SergeyKanzhelev 
Thanks for your reply. I tried exactly you mentioned but it's not working. Initialize didn't hit. I'm using .net core 2 console application. I really appreciate if you can try and suggest  working solution.

**Comment by stpriyanka** [comment]
Well, that logic works for me only after adding ```min/max LogLevel``` or both to trigger this rule.
 ```  var rule = new LoggingRule("*", NLog.LogLevel.Trace, LogLevel.Fatal, target); ```

**Comment by SergeyKanzhelev** [comment]
I'm closing this PR. If initializers are not being called - please file an issue for this to investigate

**Pull request closed without merging**
