### PR TITLE
Potential fix for issue 29

### PR DESCRIPTION
**Pull request by ericjmooney**
This is a potential fix for issue 29 which I reported recently.
(https://github.com/Microsoft/ApplicationInsights-dotnet-logging/issues/29)

### CODE REVIEW

**Comment by abaranch** [comment]
Thank you for your contribution.
Do you know if values for duplicate keys are different? Why do we want to add both? Wouldn't that be better to ignore second pair?

**Comment by ericjmooney** [comment]
I don't have enough run time on this solution (yet) to have a good idea that the values for duplicate keys might be the same or different.  My goal here is to guard against throwing away potentially useful data, and since I was unable to determine where the duplicate values are coming from I thought this was the safest solution.

**Comment by abaranch** [comment]
1. We can consider checking the value and if they are the same , do not add
2. Could you please add a unit test for it?

**Comment by ericjmooney** [comment]
Both are good suggestions...I will implement and create a new pull request soon.
Thank you.

**Pull request closed without merging**
